import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Serve the 'dist' folder generated by 'npm run build'
app.use(express.static(path.join(__dirname, 'dist')));

// Ensure all routes (like /connect or /agents) redirect to index.html for the React router
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Linker Press is live on port ${PORT}`);
});
